title: Smart Work Learning
# email: 
# twitter: 
# instagram: 
copyright: Copyright &copy; 2021 Smart Work Learning. All rights reserved.
google-analytics: UA-154771534-2
formspree: mbjzjqew
plugins: 
    - jekyll-feed
    - jekyll-sitemap
    - jekyll-seo-tag
